# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformInstaller@0'
  displayName: "Terraform Installation"
  inputs:
    terraformVersion: 'latest'

- task: TerraformCLI@0
  displayName: "Terraform Init - Azure Backend"
  inputs:
    command: 'init'
    backendType: 'azurerm'
    backendServiceArm: 'Azure for Students(d76415fd-d1f3-4359-8d5e-6121b38f3ad8)'
    backendAzureRmSubscriptionId: 'd76415fd-d1f3-4359-8d5e-6121b38f3ad8'
    allowTelemetryCollection: true

- task: TerraformCLI@0
  displayName: "Terraform Plan - Plan of Action"
  inputs:
    command: 'plan'
    environmentServiceName: 'Azure for Students(d76415fd-d1f3-4359-8d5e-6121b38f3ad8)'
    providerAzureRmSubscriptionId: 'd76415fd-d1f3-4359-8d5e-6121b38f3ad8'
    runAzLogin: true
    allowTelemetryCollection: true

- task: TerraformCLI@0
  displayName: "Terraform Apply - Deployment of Infrastructure"
  inputs:
    command: 'apply'
    environmentServiceName: 'Azure for Students(d76415fd-d1f3-4359-8d5e-6121b38f3ad8)'
    providerAzureRmSubscriptionId: 'd76415fd-d1f3-4359-8d5e-6121b38f3ad8'
    runAzLogin: true
    allowTelemetryCollection: true
